### ISSUE TITLE
More robust error handling

### ISSUE THREAD

**Issue by wojtekpolska** [RiiConnect24/RiiTag-RPC#14]
![image](https://user-images.githubusercontent.com/58272360/126004644-f7b82a34-9541-4bcd-accc-d875366fb208.png)
then after pressing enter it says loading, but it loads the wrong version (1.1.3 instead of 1.1.4)
![image](https://user-images.githubusercontent.com/58272360/126004797-628dbc38-4e2c-4207-8532-ae9ffef78586.png)

(i downloaded 1.1.4 from github)

and it never loads

I redownloaded it MULTIPLE TIMES and im 100% sure i clicked the 1.1.4 version link

**Comment by TheShadowEevee** [comment]
You can try just ignoring the error. As for the version, apparently it wasn't updated in the app; just ignore it as it should be 1.1.4.

**Comment by wojtekpolska** [comment]
but it doesn't load at all

it stays like that saying "Loading"

**Comment by TheShadowEevee** [comment]
How are you running the exe?

**Comment by wojtekpolska** [comment]
double-clicking on it 

but it seems to start working now every time i open it

**Comment by wojtekpolska** [comment]
@TheShadowEevee there are other problems tho
if i keep it opened for too long this happens:
![image](https://user-images.githubusercontent.com/58272360/126009296-150a7d8b-9ade-4f3c-8e6a-f4ae182a8ea0.png)

**Comment by DismissedGuy** [comment]
Please try closing the program, removing the cache directory and then making sure that your discord client is running.

In your discord settings, unlink/remove the application's access to your discord account.

Finally, re-run the exe. That should force the program to run through the authentication flow again, hopefully solving your issues.

**Comment by wojtekpolska** [comment]
my discord id is wojtekpolska#5541

**Comment by DismissedGuy** [comment]
Okay, so I think I found the issue.

"new_riitag" is None when this error occurs, but because the value of that var is set to be equal to "self._last_riitag" and that statement does not get executed when "self._last_riitag" is None, the only way for "new_riitag" to be None is for the "fetch_user" method on the user object to return none when it's time to do a new riitag check. This method returns None if and only if an HTTPError occurs, which means that this is a case of the server failing and the program not handling it properly.

I looked into a couple of sentry reports about this same error and sure enough:
```
GET http://tag.rc24.xyz/<user id here>/json [502]

{reason: Bad Gateway}
```

I can't fix the issue on the server side, but I can make the program more resistant to VPS shenanigans. Not sure when I'll get to actually fixing this though, don't expect too much of it. In the meantime, you can just ignore the error and/or restart the program when it happens.
