### ISSUE TITLE
Always says "Window Too Small"

### ISSUE THREAD

**Issue by Greeg0** [RiiConnect24/RiiTag-RPC#16]
When I run RiiTag-RPC (I run from source code), it always says window too small EVEN if I am maximized and my monitor is 1920x1080.

This is on Fedora Linux 36 Running GNOME 42.1
with gnome-terminal

Temporary Solution: For now, and what I will probably do from now on, is to run the program in it's own TTY.

**Comment by DismissedGuy** [comment]
I just tested the latest version from source myself, and I'm having no issues on Pop!_OS 22.04, using both gnome-terminal and kitty.

Since we don't actually do any dependency pinning except for the Sentry SDK, can you try the latest prebuilt release and see if that works? If it does, I might have to downgrade prompt_toolkit, since that handles everything related to drawing the menus.

**Comment by DismissedGuy** [comment]
Closing since there has been no response. Feel free to reopen if this issue still affects you.
