### ISSUE TITLE
Does not open browser

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/RiiTag-RPC#47]
If run by normal user, it says it opened the browser while it did not.
When run by sudo, it infinitely connects.

I am trying with the ubuntu 22.04 newest release.
I am however on EndeavourOS Linux.

![wwww](https://github.com/RiiConnect24/RiiTag-RPC/assets/147919489/83ba3407-0ea3-4422-aa8b-454169c8f975)

**Comment by malmeloo** [comment]
Hmm, strange. I haven't tried this myself, but I think it should be possible to explicitly specify a browser executable using `BROWSER=/path/to/executable python3 start.py`.  `BROWSER=$(which xdg-open) ...` might also work (if you have it installed). Let me know if that fixes it, this should only be a one-time operation anyway.

Edit: running with sudo will definitely not work, it needs to connect to a unix socket in your user's home directory, so the program will be looking in the wrong location.

**Comment by ghost** [comment]
Couldn't use that ``python3 start.py`` so instead i went with, ``BROWSER=/usr/bin/firefox ./riitag-rpc`` and got nothing. I also tried ``BROWSER=$(which xdg-open) ./riitag-rpc`` and i got ``/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq``. That is all I have.

**Comment by malmeloo** [comment]
Oh sorry, I thought you were running it from source. Could you try that actually? I've seen people who are running Arch have similar issues in the past, and that usually fixed it. IIRC the issue is that the bundling tool we use dynamically loads some libraries from the host, but Arch usually ships much newer versions of those libraries than whatever Ubuntu had when building the application.

If you have python3 (any recent version) installed:

```
python3 -m venv venv
. ./venv/bin/activate
pip3 install -U -r requirements.txt
python3 start.py
```

That should get you 90% of the way there.

**Comment by ghost** [comment]
I did that, now it enters and all and after logging in it throws some runtime errors here and there interrupting the overall gui. Albeit it may work and I am yet to check that.

**Comment by malmeloo** [comment]
Glad to hear it at least boots up now. I thought I fixed all of those errors, but it appears not. If it's the same issue I think it is, the program should still work. If it doesn't, feel free to open a new issue.
